name = "VBMC"
uuid = "1064e537-9ee1-43d8-887b-42e480a72de7"
authors = ["Jaan Erik Pihel"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
